---
version: 0.2
phases:
  install:
    commands:
      - echo "Installing Needed Software"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "running build"
      - python app.py 3 4 add
  post_build:
    commands:
      - echo "Build Completed"
artifacts:
  files:
    - "**/*"
